### ISSUE TITLE
Add Support for tests written in yaml

### ISSUE THREAD

**Issue by oconnormi** [testify/Parsers#1]
It would be great to support yaml as a test format, it is simpler and more compact than the current xml based format.
An example test file:

``` yaml
testcase:
  endpoint: "ldap://localhost:384"
  type: LdapProcessor
  test:
    operation: add
    bindDn: "cn=admin,ou=users,dc=example,dc=com"
    password: admin
    ignoreErrors: true
    file: "foo.ldif"
  assertions:
  - ValidSoapAssertion
  - NotSoapFaultAssertion
```

this can be parsed from a file using a library like SnakeYaml.

Current challenges to implementing this are that many of the processors are expecting the test data to be delivered in xml format. It is fairly trivial to transform yaml format into xml, however it would probably be better to have an internal format that is used by any component that is not a test parser
